"""Rendre les champs optionnels

Revision ID: d340e9dad93f
Revises: 13ca4be435c0
Create Date: 2024-10-07 02:26:06.234140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd340e9dad93f'
down_revision = '13ca4be435c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poste', schema=None) as batch_op:
        batch_op.alter_column('missions',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('competences',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poste', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('competences',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('missions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
